name: Update GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 또는 개인 PAT를 여기로 넣어도 됨

    steps:
      - uses: actions/checkout@v3

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Logic-Phantom
          UTC_OFFSET: 9
          AUTO_PUSH: false

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-summary-card-output/
          git commit -m "Update profile summary cards [skip ci]" || echo "No changes to commit"
          git push

