name: Update GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Logic-Phantom
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}    # 이 부분 꼭 넣어야 합니다.
          UTC_OFFSET: 9

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-summary-card-output/
          git commit -m "Update profile summary cards [skip ci]" || echo "No changes to commit"
          git push
